import { useEffect, useState } from "react";
import { Check, Copy, Gift, LoaderCircle } from "lucide-react";
import { fetchReferralCode, fetchReferrals, getReferralLink } from "../api";

function date(value) { const parsed = new Date(value); return value && !Number.isNaN(parsed.getTime()) ? parsed.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "Not available"; }

export default function ReferralsPage() {
  const [link, setLink] = useState(""); const [referrals, setReferrals] = useState([]); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetchReferralCode(), fetchReferrals()]).then(([codeResponse, referralResponse]) => { const code = codeResponse?.data?.referral_code; if (code) setLink(getReferralLink(code)); const data = referralResponse?.data; setReferrals(Array.isArray(data) ? data : data?.items || data?.results || []); }).catch((err) => setError(err.message || "Could not load referrals.")).finally(() => setLoading(false)); }, []);
  const copy = async () => { try { await navigator.clipboard.writeText(link); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setError("Could not copy the referral link."); } };
  return <main className="min-h-screen bg-slate-50 px-6 pb-24 pt-32 sm:px-8 lg:px-16"><div className="mx-auto max-w-5xl"><p className="mb-3 text-xs font-bold uppercase tracking-[0.3em] text-rose-500">Bring someone along</p><h1 className="font-display text-4xl font-semibold tracking-tight text-slate-950 sm:text-6xl">Your <em className="text-amber-500">referrals.</em></h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-500">Share a private invite link with someone who would love to travel with us.</p>{error && <p className="mt-6 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-600" role="alert">{error}</p>}<section className="mt-10 rounded-[1.5rem] bg-slate-950 p-6 text-white shadow-xl shadow-slate-950/15 sm:p-8"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-amber-300 text-slate-950"><Gift size={22} /></span><div><h2 className="font-display text-3xl font-semibold">Invite a fellow traveller</h2><p className="mt-1 text-sm text-white/55">Your referral code stays hidden inside the link.</p></div></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><input readOnly value={link ? "Private invite link ready" : "Preparing your invite link..."} className="min-w-0 flex-1 rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm text-white/70 outline-none" aria-label="Referral link status" /><button onClick={copy} disabled={!link || loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-amber-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-amber-200 disabled:opacity-50">{copied ? <Check size={17} /> : <Copy size={17} />}{copied ? "Copied" : "Copy invite link"}</button></div></section><section className="mt-12"><h2 className="font-display text-3xl font-semibold text-slate-950">Invite history</h2>{loading ? <div className="mt-6 flex justify-center text-slate-500"><LoaderCircle className="animate-spin" size={24} /></div> : referrals.length ? <div className="mt-5 divide-y divide-slate-200 border-y border-slate-200">{referrals.map((referral) => <article key={referral.id} className="flex flex-col justify-between gap-3 py-5 sm:flex-row sm:items-center"><div><h3 className="font-semibold text-slate-900">{referral.referred_customer?.name || "Invited traveller"}</h3><p className="mt-1 text-xs text-slate-500">Invited {date(referral.created_at)} · {referral.referred_customer?.email || referral.referred_customer?.mobile || "Contact unavailable"}</p></div><span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold uppercase tracking-wider text-amber-700">{referral.status || "Pending"}</span></article>)}</div> : <p className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-500">No referrals yet.</p>}</section></div></main>;
}