import { useEffect, useState } from "react";
import { ArrowUpRight, Heart, LoaderCircle, Trash2 } from "lucide-react";
import { fetchWishlist, removeFromWishlist } from "../api";
import { useTravel } from "../contexts/TravelContext";

function WishlistCard({ item, onRemove }) {
  const [removing, setRemoving] = useState(false);
  const remove = async () => { setRemoving(true); try { await onRemove(item); } finally { setRemoving(false); } };
  return <article className="group overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-lg shadow-slate-950/5 transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-56 overflow-hidden bg-slate-200"><img className="h-full w-full object-cover transition duration-700 group-hover:scale-105" src={item.banner?.image || "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=900&q=85"} alt={item.title || item.destination || "Saved journey"} /><div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 to-transparent" /><span className="absolute bottom-4 left-4 rounded-full bg-white/15 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.2em] text-white backdrop-blur">{item.type || "Journey"}</span><Heart className="absolute right-4 top-4 text-rose-400" size={21} fill="currentColor" /></div><div className="p-5"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-rose-500">{item.tour_code || item.season_name || item.destination}</p><h2 className="mt-2 font-display text-2xl font-semibold text-slate-950">{item.title || "Saved journey"}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{item.description || `A journey through ${item.destination || "somewhere wonderful"}.`}</p><div className="mt-5 flex items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">Saved {item.wishlisted_at ? new Date(item.wishlisted_at).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "recently"}</span><div className="flex items-center gap-2"><button onClick={remove} disabled={removing} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 text-slate-500 transition hover:border-rose-300 hover:text-rose-500 disabled:opacity-50" aria-label={`Remove ${item.title || "journey"} from wishlist`} title="Remove from wishlist">{removing ? <LoaderCircle size={16} className="animate-spin" /> : <Trash2 size={16} />}</button><a href={`/journey/${item.slug || item.package_id}`} className="grid h-9 w-9 place-items-center rounded-xl bg-amber-300 text-slate-950 transition hover:bg-amber-200" aria-label={`View ${item.title || "journey"}`} title="View journey"><ArrowUpRight size={17} /></a></div></div></div></article>;
}

export default function WishlistPage() {
  const { user } = useTravel();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetchWishlist().then((response) => { const data = response?.data; setItems(Array.isArray(data) ? data : data?.items || data?.results || []); }).catch((err) => setError(err.message || "Could not load your wishlist.")).finally(() => setLoading(false)); }, [user]);
  const remove = async (item) => { try { await removeFromWishlist(item.slug || item.package_id); setItems((current) => current.filter((saved) => saved.id !== item.id)); } catch (err) { setError(err.message || "Could not remove this journey."); } };
  return <main className="min-h-screen bg-slate-50 px-6 pb-24 pt-32 sm:px-8 lg:px-16"><div className="mx-auto max-w-6xl"><p className="mb-3 text-xs font-bold uppercase tracking-[0.3em] text-rose-500">Saved for later</p><div className="flex items-end justify-between gap-5 border-b border-slate-200 pb-8"><div><h1 className="font-display text-4xl font-semibold tracking-tight text-slate-950 sm:text-6xl">Your <em className="text-amber-500">wishlist.</em></h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-500">The journeys that caught your eye, kept together until you are ready to go.</p></div><Heart className="hidden text-rose-400 sm:block" size={34} fill="currentColor" /></div>{error && <p className="mt-6 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-600" role="alert">{error}</p>}{loading ? <div className="flex justify-center py-20 text-slate-500"><LoaderCircle className="animate-spin" size={25} /></div> : items.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <WishlistCard key={item.id} item={item} onRemove={remove} />)}</div> : <div className="mt-10 rounded-[1.5rem] border border-dashed border-slate-300 bg-white p-12 text-center"><Heart className="mx-auto text-slate-300" size={32} /><h2 className="mt-4 font-display text-2xl font-semibold text-slate-800">Nothing saved yet</h2><p className="mt-2 text-sm text-slate-500">Tap the heart on a journey to keep it close.</p><a href="/#journeys" className="mt-6 inline-flex rounded-xl bg-amber-300 px-4 py-3 text-sm font-bold text-slate-950">Explore journeys</a></div>}</div></main>;
}